CREATE TABLE ALUNOS (
  ALUNO INT IDENTITY(1, 1) PRIMARY KEY,
  NOME_COMPL VARCHAR(100),
  IDADE INT,
  CIDADE VARCHAR(100),
  COD_TURMA INT,
  NOME_RESP VARCHAR(100),
  FOREIGN KEY (TURMA) REFERENCES TURMAS(COD_TURMA)
);