CREATE TABLE PRESENCA (
  ID INT IDENTITY(1, 1) PRIMARY KEY,
  COD_DOCENTE INT,
  ALUNO INT,
  PRESENÇA VARCHAR(1),
  DIA_SEMANA INT,
  DATA_DA_CHAMADA VARCHAR(30),
  FOREIGN KEY (COD_DOCENTE) REFERENCES DOCENTES(COD_DOCENTE),
  FOREIGN KEY (ALUNO) REFERENCES ALUNOS(ALUNO)
);