CREATE TABLE TURMAS (
  COD_TURMA INT IDENTITY(1, 1) PRIMARY KEY,
  COD_DOCENTE INT,
  DATA_INSERCAO DATETIME,
  NOME_TURMA VARCHAR(10),
  GRADE VARCHAR(10),
  SERIE VARCHAR(10),
  FOREIGN KEY (COD_DOCENTE) REFERENCES DOCENTES(COD_DOCENTE)
);